# ============================================================================
# dsh-setup.ps1 — 一键把本套 DSH 插件/配置/启动器装到新电脑
# 适用：已运行过 `npx -y @deepseek-ai/dsh web` 的 Windows + Node 22+ 机器
# 用法：powershell -ExecutionPolicy Bypass -File setup.ps1 [-SkipSkills] [-SkipLauncher]
# ============================================================================
param(
  [switch]$SkipSkills,
  [switch]$SkipLauncher
)

$ErrorActionPreference = "Stop"
$KitRoot = $PSScriptRoot

function Write-Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "  [!] $msg" -ForegroundColor Yellow }

# ---------- 1. 预检 ----------
Write-Step "预检"
$nodeVer = node --version 2>$null
if (-not $nodeVer) { Write-Host "[ERR] 未找到 Node.js，请先安装 Node 22+（https://nodejs.org）" -ForegroundColor Red; exit 1 }
Write-Ok "Node: $nodeVer"

$profileDir = Join-Path $env:USERPROFILE ".dsh\profiles\web"
$profilePkg  = Join-Path $profileDir "package.json"
if (-not (Test-Path $profilePkg)) {
  Write-Host "[ERR] 未检测到 DSH web profile（$profileDir）" -ForegroundColor Red
  Write-Host "请先执行一次：npx -y @deepseek-ai/dsh web"
  Write-Host "看到 'dsh web: http://127.0.0.1:3080' 后按 Ctrl+C 退出，再重跑本脚本。"
  exit 1
}
Write-Ok "DSH profile 已存在"

$dshCmd = if (Get-Command dsh -ErrorAction SilentlyContinue) { "dsh" } else { "npx -y @deepseek-ai/dsh" }
Write-Ok "dsh 命令: $dshCmd"

# ---------- 2. pnpm ----------
Write-Step "准备 pnpm"
$npmGlobal = npm prefix -g 2>$null
try { corepack enable --install-directory $npmGlobal 2>&1 | Out-Null } catch {}
$env:PATH = "$npmGlobal;" + $env:PATH
if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
  Write-Host "[ERR] pnpm 不可用（corepack enable 失败），请检查 Node 安装" -ForegroundColor Red; exit 1
}
Write-Ok "pnpm $((pnpm --version 2>$null))"

# ---------- 3. cordis.patch.yml（agent-instructions + MCP，路径动态化） ----------
Write-Step "写入 profile 补丁（agent-instructions 只读 AGENTS.md + 学术检索 MCP）"
$hasUv    = [bool](Get-Command uv -ErrorAction SilentlyContinue)
$hasSkill = (-not $SkipSkills) -and (Test-Path (Join-Path $KitRoot "skills\nature-academic-search\mcp-server"))
$patchLines = @(
  "# Generated by dsh-setup.ps1 - do not edit manually.",
  "# agent-instructions: 只读 AGENTS.md（CLAUDE.md 不读）",
  "- id: agent-instructions",
  "  config:",
  "    maxBytes: 65536",
  "    instructionFileCandidates:",
  "      - AGENTS.md",
  "    localInstructionFileCandidates: []"
)
if ($hasUv -and $hasSkill) {
  $uvPath    = (Get-Command uv).Source
  $uvYaml    = $uvPath -replace '\\','\\'
  $skillRoot = (Join-Path $env:USERPROFILE ".dsh\skills\nature-academic-search\mcp-server") -replace '\\','\\'
  $patchLines += @(
    "",
    "# Academic-search MCP（nature-academic-search 技能自带，uv 运行）",
    "- insert:",
    "    - id: mcp-academic-search",
    "      name: '@deepseek-ai/dsh-mcp-client'",
    "      config:",
    "        serverName: academic-search",
    "        transport: stdio",
    "        command: $uvYaml",
    "        args:",
    "          - run",
    "          - --python",
    "          - '3.11'",
    "          - --no-project",
    "          - --directory",
    "          - $skillRoot",
    "          - --with",
    "          - 'mcp>=1.0.0,<2.0.0'",
    "          - --with",
    "          - 'requests>=2.28.0,<3.0.0'",
    "          - --with",
    "          - 'toml>=0.10.2,<2.0.0'",
    "          - --with",
    "          - 'lxml>=4.9.0,<5.0.0'",
    "          - --with",
    "          - 'pybliometrics>=4.4.1,<5.0.0'",
    "          - python",
    "          - academic_search_server.py",
    "        env:",
    "          PUBMED_EMAIL: !!js process.env.PUBMED_EMAIL ?? ''"
  )
  Write-Ok "MCP 配置已包含（uv + 技能 mcp-server 就绪）"
} else {
  $why = if ($hasUv) { "技能未复制" } else { "未检测到 uv" }
  Write-Warn "跳过 MCP 配置（$why）；装好 uv 后可手动补，见 README"
}
$patchLines | Set-Content -LiteralPath (Join-Path $profileDir "cordis.patch.yml") -Encoding UTF8
Write-Ok "cordis.patch.yml 已写入"

# ---------- 4. npm 插件（dsh-web-ui 全家桶） ----------
Write-Step "安装 npm 插件（dsh-web-ui 全家桶）"
function Invoke-DshPlugin($argsLine) {
  & cmd /c "$dshCmd plugin --profile web $argsLine 2>&1"
}
Invoke-DshPlugin "add @linxin666/dsh-web-ui-all@0.1.12" | Out-Host
$wsFile = Join-Path $profileDir "pnpm-workspace.yaml"
$needsBuildAllow = $LASTEXITCODE -ne 0
if ((Test-Path $wsFile) -and ((Get-Content $wsFile -Raw) -match "set this to true or false")) { $needsBuildAllow = $true }
if ($needsBuildAllow) {
  Write-Warn "检测到 allowBuilds 需要确认，自动放行 cloudflared/cpu-features/ssh2 后重试"
  $content = ""
  if (Test-Path $wsFile) { $content = Get-Content $wsFile -Raw }
  $content = $content -replace 'cloudflared: set this to true or false', 'cloudflared: true'
  $content = $content -replace 'cpu-features: set this to true or false', 'cpu-features: true'
  $content = $content -replace 'ssh2: set this to true or false', 'ssh2: true'
  if ($content -notmatch 'allowBuilds:') {
    $content += "`nallowBuilds:`n  cloudflared: true`n  cpu-features: true`n  ssh2: true`n"
  }
  Set-Content -LiteralPath $wsFile -Value $content -Encoding UTF8
  Invoke-DshPlugin "add @linxin666/dsh-web-ui-all@0.1.12" | Out-Host
}
Write-Ok "dsh-web-ui-all 安装完成"

# ---------- 5. 本地 git 插件（link:） ----------
Write-Step "安装本地插件（drag-and-drop / chat-import / file-claim / file-mentions / plugin-anydoc）"
$localDirs = @("dsh-drag-and-drop","dsh-chat-import","dsh-file-claim","dsh-file-mentions","dsh-plugin-anydoc")
foreach ($d in $localDirs) {
  $p = Join-Path $KitRoot "plugins-src\$d"
  if (-not (Test-Path (Join-Path $p "package.json"))) { Write-Warn "跳过缺失的 $d"; continue }
  Write-Host "  -> $d"
  Invoke-DshPlugin "add `"$p`"" | Out-Host
}
Write-Ok "本地插件已登记"

# ---------- 6. link 插件依赖修复（junction，等同 peer 依赖补齐） ----------
Write-Step "修复 link 插件的运行时依赖（node_modules junction）"
$srcRoot = Join-Path $KitRoot "plugins-src"
$stage   = Join-Path $srcRoot ".dsh-runtime-deps"
$shared  = Join-Path $srcRoot "node_modules"
if (-not (Test-Path (Join-Path $stage "node_modules\@deepseek-ai\dsh-tools"))) {
  Write-Host "  安装运行时依赖到 $stage ..."
  Push-Location $srcRoot
  npm install --prefix $stage --no-audit --no-fund `
    "@deepseek-ai/dsh-tools@0.1.0-rc.6" `
    "@deepseek-ai/dsh-client-locale@0.1.0-rc.6" `
    "@deepseek-ai/cordis@^4.0.1" `
    "react@18.2.0" `
    "@firecrawl/anydoc@^0.1.8" 2>&1 | Select-Object -Last 3 | Out-Host
  Pop-Location
}
if (Test-Path $shared) { Remove-Item $shared -Force -Recurse -ErrorAction SilentlyContinue }
New-Item -ItemType Junction -Path $shared -Target (Join-Path $stage "node_modules") | Out-Null
Write-Ok "junction 就绪"

# ---------- 7. Everything（拖拽路径解析） ----------
Write-Step "安装 Everything 便携版（拖文件到对话框自动定位路径用）"
$evDir = Join-Path $env:USERPROFILE "Everything-Portable"
if (-not (Test-Path $evDir)) { Copy-Item (Join-Path $KitRoot "everything-portable") $evDir -Recurse -Force }
$userPath = [Environment]::GetEnvironmentVariable("Path","User")
if ($userPath -notmatch [regex]::Escape($evDir)) {
  [Environment]::SetEnvironmentVariable("Path", $userPath.TrimEnd(';') + ";" + $evDir, "User")
  Write-Ok "Everything 目录已加入用户 PATH"
}
$env:PATH = "$evDir;" + $env:PATH
try {
  Start-Process (Join-Path $evDir "everything.exe") -Verb RunAs -ErrorAction Stop
  Write-Ok "Everything 已启动（如弹 UAC 请点'是'，NTFS 全盘索引需要管理员）"
} catch {
  Write-Warn "Everything 启动失败，可稍后手动打开 $evDir\everything.exe"
}

# ---------- 8. 技能（可选） ----------
if (-not $SkipSkills) {
  Write-Step "复制技能（~/.dsh/skills）"
  $dst = Join-Path $env:USERPROFILE ".dsh\skills"
  if (Test-Path (Join-Path $KitRoot "skills")) {
    New-Item -ItemType Directory -Path $dst -Force | Out-Null
    Copy-Item (Join-Path $KitRoot "skills\*") $dst -Recurse -Force
    Write-Ok "技能已复制"
  }
} else { Write-Warn "已跳过技能复制" }

# ---------- 9. 启动器（可选） ----------
if (-not $SkipLauncher) {
  Write-Step "安装 dsh-launcher 启动器"
  $msi = Join-Path $KitRoot "launcher\dsh-launcher-0.1.6.msi"
  if (Test-Path $msi) {
    Write-Host "  运行 MSI 安装（如弹 UAC 请点'是'）..."
    Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qb /norestart" -Wait
    Write-Ok "dsh-launcher 安装完成"
  } else { Write-Warn "未找到 MSI，跳过（可手动安装 launcher\dsh-launcher-windows.zip 便携版）" }
} else { Write-Warn "已跳过启动器安装" }

# ---------- 10. 完成 ----------
Write-Step "完成"
Write-Host @"
所有组件已就位。接下来：
1. 启动 DSH：打开 dsh-launcher（或命令行 npx -y @deepseek-ai/dsh web）
2. 浏览器打开 http://127.0.0.1:3080 后按 Ctrl+F5 硬刷新
3. 侧边栏应出现：任务看板 / Git图谱 / 右侧面板 / 实时token统计 / 皮肤中心 / SSH
4. 配置你自己的 API 凭据（DSH 设置里）

注意事项：
- 本安装包目录（$KitRoot）安装后【不要移动/删除】——本地插件是链接到这里的
- Everything 需保持运行（最小化到托盘），否则拖拽定位大目录会失效
- 同学需要自己的 API key；MCP 学术检索需要 uv（astral.sh/uv）
"@ -ForegroundColor Green
